name = "booking-worker"
main = "src/index.ts"
compatibility_date = "2026-02-09"

kv_namespaces = [
  { binding = "BOOKING_KV", id = "8b086b812d2148568884ed6c7611db4d", preview_id = "REPLACE_WITH_YOUR_KV_PREVIEW_ID" }
]

[vars]
COOKIE_SECURE = "false"
